# .github/workflows/create.yml

name: 'Terraform Create Infrastructure'

on:
  workflow_dispatch:

jobs:
  create-infra:
    name: 'Create Infrastructure'
    runs-on: ubuntu-latest
    env:
      TF_VAR_aws_region: us-east-1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="environment=aws"